Fixed a bug in the configure script which got confused when emacs (or Xemacs) are referred to by their full pathname.  Thanks to Sergio Antoy.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -599,12 +599,49 @@ test -z "$INSTALL_PROGRAM" && INSTALL_PROGRAM='${INSTALL}'
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 
+# Extract the first word of "basename", so it can be a program name with args.
+set dummy basename; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:606: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_BASENAME'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$BASENAME" in
+  /*)
+  ac_cv_path_BASENAME="$BASENAME" # Let the user override the test with a path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_BASENAME="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+BASENAME="$ac_cv_path_BASENAME"
+if test -n "$BASENAME"; then
+  echo "$ac_t""$BASENAME" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$BASENAME x" = " x"
+then
+  { echo "configure: error: Cannot find program "basename" on your patch.
+Hint: Try setting BASENAME environment variable or fixing your PATH." 1>&2; exit 1; }
+fi
+
 for ac_prog in emacs xemacs
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:608: checking for $ac_word" >&5
+echo "configure:645: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_EMACS'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -632,7 +669,13 @@ fi
 test -n "$EMACS" && break
 done
 
-if test "$EMACS" = xemacs
+if test "$EMACS x" = " x"
+then
+  { echo "configure: error: Cannot find emacs in your path.
+Hint: Try setting EMACS environment variable or fixing your PATH." 1>&2; exit 1; }
+fi
+RESULT=`$BASENAME $EMACS`
+if test "$RESULT" = xemacs
 then
   if $EMACS -batch -q --vanilla
   then
@@ -641,16 +684,12 @@ then
   else
     EMACSFLAGS="-q -no-site-file"  # Still running Xemacs 19.x
   fi
-else if test "$EMACS" = emacs
+else if test "$RESULT" = emacs
 then
   EMACSFLAGS=""
   
-else
-  { echo "configure: error: Cannot find emacs in your path.
-Hint: Try setting EMACS environment variable or fixing your PATH." 1>&2; exit 1; }
 fi
 fi
-
 EXTRA_SRCS=""
 EXTRA_OBJS=""
 echo -n checking for timer.el...
@@ -810,6 +849,7 @@ s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_DATA@%$INSTALL_DATA%g
+s%@BASENAME@%$BASENAME%g
 s%@EMACS@%$EMACS%g
 s%@EMACSFLAGS@%$EMACSFLAGS%g
 s%@EXTRA_SRCS@%$EXTRA_SRCS%g
